# Generated by Django 5.1.5 on 2025-01-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobeChat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globehistory',
            name='user',
        ),
        migrations.AddField(
            model_name='globehistory',
            name='username',
            field=models.ForeignKey(default='amir1234', on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
