# Generated by Django 5.1.5 on 2025-01-26 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobeChat', '0002_remove_globehistory_user_globehistory_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globehistory',
            name='color',
            field=models.CharField(default='red', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globehistory',
            name='user',
            field=models.ForeignKey(default='red', on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globehistory',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
