# Generated by Django 5.1.5 on 2025-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobeChat', '0003_globehistory_color_globehistory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globehistory',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='globehistory',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
